/* SPDX-License-Identifier: GPL-3.0-or-later
   Copyright (C) 2026 Maurizio Cammalleri */
/*
 * gpu.c - optional integrated GPU for quantized products (see gpu.h).
 *
 * Built with the GPU only when the build compiled the shaders
 * (JANAS_GPU_SPV) and the Vulkan headers are present; the Vulkan loader
 * itself is opened at run time, so the library never depends on it.
 */
#include "gpu.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(JANAS_GPU_SPV) && __has_include(<vulkan/vulkan.h>)

#define VK_NO_PROTOTYPES
#include <dlfcn.h>
#include <immintrin.h>
#include <pthread.h>
#include <stdatomic.h>
#include <unistd.h>
#include <vulkan/vulkan.h>

#include "q4k_matvec.h" /* janas_spv_q4k_matvec, generated by build.sh */
#include "q6k_matvec.h" /* janas_spv_q6k_matvec */
#include "expert_act.h" /* janas_spv_expert_act */

#define MAX_REGIONS 8
#define MAX_PENDING 64
#define MAX_XCACHE 8
#define X_STAGE_BYTES ((size_t)8 << 20)
#define Y_STAGE_BYTES ((size_t)32 << 20)
#define ROWS_PER_GROUP 64 /* local_size_x of the shader */
#define NV_PER_GROUP 8    /* its NV */
#define GPU_BLOCK 320     /* a Q8_K block in the shader's layout */
#define SHARE_SLOTS 64
#define MAX_GROUP 64

/* instance-level functions, then device-level ones */
#define VK_INSTANCE_FUNCS(X)                                                   \
    X(vkDestroyInstance)                                                       \
    X(vkEnumeratePhysicalDevices)                                              \
    X(vkGetPhysicalDeviceProperties)                                           \
    X(vkGetPhysicalDeviceProperties2)                                          \
    X(vkGetPhysicalDeviceFeatures2)                                            \
    X(vkGetPhysicalDeviceMemoryProperties)                                     \
    X(vkGetPhysicalDeviceQueueFamilyProperties)                                \
    X(vkEnumerateDeviceExtensionProperties)                                    \
    X(vkCreateDevice)                                                          \
    X(vkGetDeviceProcAddr)
#define VK_DEVICE_FUNCS(X)                                                     \
    X(vkDestroyDevice)                                                         \
    X(vkGetDeviceQueue)                                                        \
    X(vkCreateBuffer)                                                          \
    X(vkDestroyBuffer)                                                         \
    X(vkGetBufferMemoryRequirements)                                           \
    X(vkAllocateMemory)                                                        \
    X(vkFreeMemory)                                                            \
    X(vkBindBufferMemory)                                                      \
    X(vkMapMemory)                                                             \
    X(vkInvalidateMappedMemoryRanges)                                          \
    X(vkFlushMappedMemoryRanges)                                               \
    X(vkGetBufferDeviceAddress)                                                \
    X(vkGetMemoryHostPointerPropertiesEXT)                                     \
    X(vkCreateShaderModule)                                                    \
    X(vkDestroyShaderModule)                                                   \
    X(vkCreatePipelineLayout)                                                  \
    X(vkDestroyPipelineLayout)                                                 \
    X(vkCreateComputePipelines)                                                \
    X(vkDestroyPipeline)                                                       \
    X(vkCreateCommandPool)                                                     \
    X(vkDestroyCommandPool)                                                    \
    X(vkAllocateCommandBuffers)                                                \
    X(vkResetCommandBuffer)                                                    \
    X(vkBeginCommandBuffer)                                                    \
    X(vkEndCommandBuffer)                                                      \
    X(vkCmdBindPipeline)                                                       \
    X(vkCmdPushConstants)                                                      \
    X(vkCmdDispatch)                                                           \
    X(vkCmdPipelineBarrier)                                                    \
    X(vkCmdCopyBuffer)                                                         \
    X(vkWaitForFences)                                                         \
    X(vkCreateFence)                                                           \
    X(vkDestroyFence)                                                          \
    X(vkResetFences)                                                           \
    X(vkGetFenceStatus)                                                        \
    X(vkQueueSubmit)

struct region {
    const uint8_t *host;
    size_t bytes;
    VkBuffer buf;
    VkDeviceMemory mem;
    VkDeviceAddress addr;
    int coherent; /* allocated regions: else flushed after host writes */
};

struct stage {
    VkBuffer buf;
    VkDeviceMemory mem;
    uint8_t *map;
    VkDeviceAddress addr;
    size_t bytes;
    int coherent; /* else invalidated before the host reads it */
};

struct pending {
    float *y;        /* the task's output */
    size_t rows, nv; /* rows computed by the GPU, vectors */
    size_t y_stride; /* the task's */
    size_t off;      /* in the Y stage */
};

/* The push constants of the shader. */
struct push {
    uint32_t w[2], x[2], y[2];
    uint32_t rows, nb, nv, xs, ys;
};

struct janas_gpu {
    void *lib;
    PFN_vkGetInstanceProcAddr gipa;
#define DECL(f) PFN_##f f;
    VK_INSTANCE_FUNCS(DECL)
    VK_DEVICE_FUNCS(DECL)
#undef DECL
    VkInstance inst;
    VkPhysicalDevice pd;
    VkDevice dev;
    VkQueue queue;
    VkShaderModule sm, sm6, sma;
    VkPipelineLayout pl;
    VkPipeline pipe, pipe6, pipea; /* Q4_K, Q6_K, expert activation */
    VkCommandPool cp;
    VkCommandBuffer cb;
    VkFence fence;
    VkPhysicalDeviceMemoryProperties mp;
    struct region reg[MAX_REGIONS];
    int n_reg;
    struct stage xs, ys;
    struct pending pend[MAX_PENDING];
    size_t n_pend;
    int busy, broken;
    char name[VK_MAX_PHYSICAL_DEVICE_NAME_SIZE];
    uint32_t sg;     /* subgroup size the shader runs with */
    int discrete;    /* weights copied to its memory, not shared */
    int host_import; /* VK_EXT_external_memory_host available */
    int sg_control;  /* the size is required (else the device's fixed one) */
    /* the GPU's share of the rows, per product shape */
    struct share {
        uint64_t key;
        float f;
        uint32_t calls, waits;
        double t_begin, t_cpu, t_wait, t_copy; /* seconds, verbose only */
        uint64_t rows_gpu, rows_all;
        uint32_t off; /* calls left on the CPU alone */
    } share[SHARE_SLOTS];
    size_t min_n;
    size_t full_n; /* from this many vectors the GPU takes every row */
    int verbose, nospin, block_wait;
    double t_waited; /* last janas_gpu_finish */
    size_t y_used;   /* bytes of the Y stage written by the last group */
    double t_conv, t_rec, t_sub; /* verbose: time in janas_gpu_begin */
    VkDeviceSize atom;           /* nonCoherentAtomSize */
    /* keep-alive: an empty dispatch every keep_us while running, so that
       the GPU does not fall asleep between products (waking it costs up to
       ~0.5 ms per submission) */
    pthread_mutex_t qlock; /* the queue is shared with the keep-alive */
    pthread_t ka;
    int ka_running;
    atomic_int ka_stop;
    atomic_int ka_wanted; /* only while passes use the GPU */
    unsigned keep_us;
    VkCommandBuffer ka_cb;
    VkFence ka_fence;
};

static double now(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec + 1e-9 * (double)ts.tv_nsec;
}

static int set_err(char *err, size_t len, const char *what, VkResult r)
{
    snprintf(err, len, "%s (%d)", what, (int)r);
    return -1;
}

/* A memory type among bits with the wanted flags, preferring cached. */
static int mem_type(const struct janas_gpu *g, uint32_t bits,
                    VkMemoryPropertyFlags want)
{
    int best = -1;
    for (uint32_t i = 0; i < g->mp.memoryTypeCount; i++) {
        VkMemoryPropertyFlags f = g->mp.memoryTypes[i].propertyFlags;
        if (!(bits & (1u << i)) || (f & want) != want)
            continue;
        if (best < 0 || (f & VK_MEMORY_PROPERTY_HOST_CACHED_BIT))
            best = (int)i;
        if (f & VK_MEMORY_PROPERTY_HOST_CACHED_BIT)
            break;
    }
    return best;
}

static VkDeviceAddress buffer_address(struct janas_gpu *g, VkBuffer b)
{
    VkBufferDeviceAddressInfo ai = {
        .sType = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO, .buffer = b};
    return g->vkGetBufferDeviceAddress(g->dev, &ai);
}

/* A mapped buffer in host-cached memory if there is any (on the Arc iGPU
   the coherent type is uncached: reading 1 MB costs ~0.9 ms and writing
   300 KB ~0.7 ms), flushed and invalidated by hand when not coherent. */
static int make_stage(struct janas_gpu *g, struct stage *s, size_t bytes,
                      int cached)
{
    VkBufferCreateInfo bi = {.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                             .size = bytes,
                             .usage =
                                 VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                 VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT};
    if (g->vkCreateBuffer(g->dev, &bi, NULL, &s->buf) != VK_SUCCESS)
        return -1;
    VkMemoryRequirements req;
    g->vkGetBufferMemoryRequirements(g->dev, s->buf, &req);
    int t = mem_type(g, req.memoryTypeBits,
                     VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                         (cached ? VK_MEMORY_PROPERTY_HOST_CACHED_BIT
                                 : VK_MEMORY_PROPERTY_HOST_COHERENT_BIT));
    if (t < 0)
        t = mem_type(g, req.memoryTypeBits,
                     VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                         VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (t < 0)
        return -1;
    s->coherent = (g->mp.memoryTypes[t].propertyFlags &
                   VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) != 0;
    VkMemoryAllocateFlagsInfo fl = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO,
        .flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT};
    VkMemoryAllocateInfo ai = {.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                               .pNext = &fl,
                               .allocationSize = req.size,
                               .memoryTypeIndex = (uint32_t)t};
    if (g->vkAllocateMemory(g->dev, &ai, NULL, &s->mem) != VK_SUCCESS ||
        g->vkBindBufferMemory(g->dev, s->buf, s->mem, 0) != VK_SUCCESS ||
        g->vkMapMemory(g->dev, s->mem, 0, VK_WHOLE_SIZE, 0, (void **)&s->map) !=
            VK_SUCCESS)
        return -1;
    s->addr = buffer_address(g, s->buf);
    s->bytes = bytes;
    if (getenv("JANAS_GPU_VERBOSE"))
        fprintf(stderr, "gpu stage %zu MiB: memory type %d, flags %#x\n",
                bytes >> 20, t, (unsigned)g->mp.memoryTypes[t].propertyFlags);
    return 0;
}

static int has_extension(struct janas_gpu *g, const char *name)
{
    uint32_t n = 0;
    g->vkEnumerateDeviceExtensionProperties(g->pd, NULL, &n, NULL);
    VkExtensionProperties *e = malloc(n * sizeof(*e));
    if (!e)
        return 0;
    g->vkEnumerateDeviceExtensionProperties(g->pd, NULL, &n, e);
    int found = 0;
    for (uint32_t i = 0; i < n && !found; i++)
        found = strcmp(e[i].extensionName, name) == 0;
    free(e);
    return found;
}

/* An integrated GPU with everything the shader needs, or -1. */
static int pick_device(struct janas_gpu *g, uint32_t *family, char *err,
                       size_t err_len)
{
    uint32_t n = 0;
    g->vkEnumeratePhysicalDevices(g->inst, &n, NULL);
    VkPhysicalDevice pds[16];
    if (n > 16)
        n = 16;
    g->vkEnumeratePhysicalDevices(g->inst, &n, pds);
    /* a discrete GPU first (memory and power of its own), then an
       integrated one; JANAS_GPU_DEVICE=integrated|discrete restricts */
    const char *want_dev = getenv("JANAS_GPU_DEVICE");
    /* the first device turned down and why, for the message: a tester
       with a GPU the engine does not take has to be able to tell why */
    char why[160] = "";
#define REJECT(what)                                                           \
    {                                                                          \
        if (!why[0])                                                           \
            snprintf(why, sizeof(why), "%.80s: %s", pp.deviceName, what);      \
        continue;                                                              \
    }
    for (int pass = 0; pass < 2; pass++)
        for (uint32_t i = 0; i < n; i++) {
            g->pd = pds[i];
            VkPhysicalDeviceProperties pp;
            g->vkGetPhysicalDeviceProperties(g->pd, &pp);
            VkPhysicalDeviceType type =
                pass == 0 ? VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
                          : VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU;
            if (pp.deviceType != type ||
                (want_dev &&
                 strcmp(want_dev, pass == 0 ? "discrete" : "integrated") != 0))
                continue;
            if (pp.apiVersion < VK_API_VERSION_1_3)
                REJECT("its driver offers Vulkan below 1.3")
            VkPhysicalDeviceVulkan13Properties p13 = {
                .sType =
                    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES};
            VkPhysicalDeviceVulkan11Properties p11 = {
                .sType =
                    VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES,
                .pNext = &p13};
            VkPhysicalDeviceProperties2 pp2 = {
                .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2,
                .pNext = &p11};
            g->vkGetPhysicalDeviceProperties2(g->pd, &pp2);
            VkPhysicalDeviceVulkan13Features f13 = {
                .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES};
            VkPhysicalDeviceVulkan12Features f12 = {
                .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES,
                .pNext = &f13};
            VkPhysicalDeviceFeatures2 f2 = {
                .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2,
                .pNext = &f12};
            g->vkGetPhysicalDeviceFeatures2(g->pd, &f2);
            if (!f12.bufferDeviceAddress || !f13.shaderIntegerDotProduct ||
                !(p11.subgroupSupportedOperations &
                  VK_SUBGROUP_FEATURE_BALLOT_BIT))
                REJECT("no buffer addresses, integer dot product or ballot")
            /* sharing host memory: needed by an integrated GPU (it reads the
               weights where they are), optional for a discrete one (it gets a
               copy in its own memory) */
            g->host_import =
                has_extension(g, VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME);
            g->discrete = type == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU;
            if (!g->discrete && !g->host_import)
                REJECT("integrated, without VK_EXT_external_memory_host")
            /* the subgroup size the shader is built for: 8 where the size can
               be chosen (Intel: fewer registers per lane), else the device's
               own if it never varies (NVIDIA: 32); JANAS_GPU_SG forces one */
            int control =
                f13.subgroupSizeControl && f13.computeFullSubgroups &&
                (p13.requiredSubgroupSizeStages & VK_SHADER_STAGE_COMPUTE_BIT);
            const char *se = getenv("JANAS_GPU_SG");
            uint32_t want = se ? (uint32_t)atoi(se) : 8, sg;
            if (control && want >= p13.minSubgroupSize &&
                want <= p13.maxSubgroupSize)
                sg = want;
            else if (control)
                sg = p11.subgroupSize;
            else if (p13.minSubgroupSize == p13.maxSubgroupSize)
                sg = p11.subgroupSize;
            else
                REJECT("subgroup size varying and not selectable")
            if (sg < 4 || sg > ROWS_PER_GROUP || (sg & (sg - 1)) != 0)
                REJECT("subgroup size not usable")
            g->sg = sg;
            g->sg_control = control;
            uint32_t nf = 0;
            g->vkGetPhysicalDeviceQueueFamilyProperties(g->pd, &nf, NULL);
            VkQueueFamilyProperties qf[16];
            if (nf > 16)
                nf = 16;
            g->vkGetPhysicalDeviceQueueFamilyProperties(g->pd, &nf, qf);
            for (uint32_t f = 0; f < nf; f++)
                if (qf[f].queueFlags & VK_QUEUE_COMPUTE_BIT) {
                    *family = f;
                    snprintf(g->name, sizeof(g->name), "%s", pp.deviceName);
                    return 0;
                }
            REJECT("no compute queue")
        }
#undef REJECT
    if (why[0])
        snprintf(err, err_len, "%s", why);
    else if (n == 0)
        snprintf(err, err_len, "Vulkan sees no GPU");
    else if (want_dev)
        snprintf(err, err_len, "no %.20s GPU, as JANAS_GPU_DEVICE asks",
                 want_dev);
    else
        snprintf(err, err_len, "Vulkan sees no integrated or discrete GPU");
    return -1;
}

static void *keep_alive(void *arg)
{
    struct janas_gpu *g = arg;
    VkSubmitInfo sub = {.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
                        .commandBufferCount = 1,
                        .pCommandBuffers = &g->ka_cb};
    int pending = 0;
    while (!atomic_load(&g->ka_stop)) {
        if (!atomic_load(&g->ka_wanted)) {
            usleep(2000);
            continue;
        }
        if (pending && g->vkGetFenceStatus(g->dev, g->ka_fence) == VK_SUCCESS) {
            g->vkResetFences(g->dev, 1, &g->ka_fence);
            pending = 0;
        }
        if (!pending) {
            pthread_mutex_lock(&g->qlock);
            pending =
                g->vkQueueSubmit(g->queue, 1, &sub, g->ka_fence) == VK_SUCCESS;
            pthread_mutex_unlock(&g->qlock);
        }
        usleep(g->keep_us);
    }
    if (pending)
        while (g->vkGetFenceStatus(g->dev, g->ka_fence) == VK_NOT_READY)
            usleep(50);
    return NULL;
}

/* An empty dispatch (no blocks: nothing read; invocation 0 writes one float
   at the start of the Y stage, unused), recorded once, for the keep-alive. */
static int record_keep_alive(struct janas_gpu *g)
{
    VkCommandBufferAllocateInfo cba = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool = g->cp,
        .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = 1};
    VkFenceCreateInfo fci = {.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    VkCommandBufferBeginInfo bb = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    if (g->vkAllocateCommandBuffers(g->dev, &cba, &g->ka_cb) != VK_SUCCESS ||
        g->vkCreateFence(g->dev, &fci, NULL, &g->ka_fence) != VK_SUCCESS ||
        g->vkBeginCommandBuffer(g->ka_cb, &bb) != VK_SUCCESS)
        return -1;
    VkDeviceAddress a = g->ys.addr + g->ys.bytes - 64;
    struct push pc = {.rows = 1, .nb = 0, .nv = 1, .xs = 0, .ys = 0};
    pc.y[0] = pc.x[0] = pc.w[0] = (uint32_t)a;
    pc.y[1] = pc.x[1] = pc.w[1] = (uint32_t)(a >> 32);
    g->vkCmdBindPipeline(g->ka_cb, VK_PIPELINE_BIND_POINT_COMPUTE, g->pipe);
    g->vkCmdPushConstants(g->ka_cb, g->pl, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                          sizeof(pc), &pc);
    g->vkCmdDispatch(g->ka_cb, 1, 1, 1);
    return g->vkEndCommandBuffer(g->ka_cb) == VK_SUCCESS ? 0 : -1;
}

/* A compute pipeline for a product shader: NV vectors per workgroup, the
   chosen subgroup size (required when the device lets it be chosen). */
static VkResult make_pipeline(struct janas_gpu *g, const uint32_t *code,
                              size_t bytes, VkShaderModule *sm,
                              VkPipeline *pipe)
{
    VkShaderModuleCreateInfo smi = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = bytes,
        .pCode = code};
    VkResult r = g->vkCreateShaderModule(g->dev, &smi, NULL, sm);
    if (r != VK_SUCCESS)
        return r;
    uint32_t spec[2] = {NV_PER_GROUP, g->sg};
    VkSpecializationMapEntry me[2] = {
        {.constantID = 0, .offset = 0, .size = 4},
        {.constantID = 1, .offset = 4, .size = 4}};
    VkSpecializationInfo si = {
        .mapEntryCount = 2, .pMapEntries = me, .dataSize = 8, .pData = spec};
    VkPipelineShaderStageRequiredSubgroupSizeCreateInfo rss = {
        .sType =
            VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO,
        .requiredSubgroupSize = g->sg};
    VkComputePipelineCreateInfo cpi = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage =
            {.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
             .pNext = g->sg_control ? &rss : NULL,
             .flags =
                 g->sg_control
                     ? VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT
                     : 0,
             .stage = VK_SHADER_STAGE_COMPUTE_BIT,
             .module = *sm,
             .pName = "main",
             .pSpecializationInfo = &si},
        .layout = g->pl};
    return g->vkCreateComputePipelines(g->dev, VK_NULL_HANDLE, 1, &cpi, NULL,
                                       pipe);
}

struct janas_gpu *janas_gpu_create(char *err, size_t err_len)
{
    struct janas_gpu *g = calloc(1, sizeof(*g));
    if (!g) {
        snprintf(err, err_len, "out of memory");
        return NULL;
    }
    g->lib = dlopen("libvulkan.so.1", RTLD_NOW | RTLD_LOCAL);
    if (!g->lib) {
        snprintf(err, err_len, "no Vulkan loader (libvulkan.so.1)");
        free(g);
        return NULL;
    }
    g->gipa = (PFN_vkGetInstanceProcAddr)dlsym(g->lib, "vkGetInstanceProcAddr");
    PFN_vkCreateInstance create_instance =
        g->gipa ? (PFN_vkCreateInstance)g->gipa(NULL, "vkCreateInstance")
                : NULL;
    VkResult r;
    VkApplicationInfo app = {.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
                             .pApplicationName = "janas",
                             .apiVersion = VK_API_VERSION_1_3};
    VkInstanceCreateInfo ici = {.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
                                .pApplicationInfo = &app};
    if (!create_instance ||
        (r = create_instance(&ici, NULL, &g->inst)) != VK_SUCCESS) {
        snprintf(err, err_len, "no Vulkan instance");
        dlclose(g->lib);
        free(g);
        return NULL;
    }
#define LOAD_I(f)                                                              \
    if (!(g->f = (PFN_##f)g->gipa(g->inst, #f)))                               \
        goto missing;
    VK_INSTANCE_FUNCS(LOAD_I)
#undef LOAD_I
    uint32_t family = 0;
    if (pick_device(g, &family, err, err_len) != 0)
        goto fail;
    g->vkGetPhysicalDeviceMemoryProperties(g->pd, &g->mp);
    VkPhysicalDeviceProperties pp;
    g->vkGetPhysicalDeviceProperties(g->pd, &pp);
    g->atom =
        pp.limits.nonCoherentAtomSize ? pp.limits.nonCoherentAtomSize : 64;

    float prio = 1.0f;
    VkDeviceQueueCreateInfo qci = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
        .queueFamilyIndex = family,
        .queueCount = 1,
        .pQueuePriorities = &prio};
    VkPhysicalDeviceVulkan13Features f13 = {
        .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES,
        .shaderIntegerDotProduct = VK_TRUE,
        .subgroupSizeControl = g->sg_control ? VK_TRUE : VK_FALSE,
        .computeFullSubgroups = g->sg_control ? VK_TRUE : VK_FALSE};
    VkPhysicalDeviceVulkan12Features f12 = {
        .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES,
        .pNext = &f13,
        .bufferDeviceAddress = VK_TRUE};
    const char *ext[] = {VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME};
    VkDeviceCreateInfo dci = {.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
                              .pNext = &f12,
                              .queueCreateInfoCount = 1,
                              .pQueueCreateInfos = &qci,
                              .enabledExtensionCount = g->host_import ? 1 : 0,
                              .ppEnabledExtensionNames = ext};
    if ((r = g->vkCreateDevice(g->pd, &dci, NULL, &g->dev)) != VK_SUCCESS) {
        set_err(err, err_len, "cannot create the Vulkan device", r);
        goto fail;
    }
#define LOAD_D(f)                                                              \
    if (!(g->f = (PFN_##f)g->vkGetDeviceProcAddr(g->dev, #f)))                 \
        goto missing;
    VK_DEVICE_FUNCS(LOAD_D)
#undef LOAD_D
    g->vkGetDeviceQueue(g->dev, family, 0, &g->queue);

    VkPushConstantRange pcr = {.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
                               .size = sizeof(struct push)};
    VkPipelineLayoutCreateInfo pli = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges = &pcr};
    if ((r = g->vkCreatePipelineLayout(g->dev, &pli, NULL, &g->pl)) !=
            VK_SUCCESS ||
        (r = make_pipeline(g, janas_spv_q4k_matvec,
                           sizeof(janas_spv_q4k_matvec), &g->sm, &g->pipe)) !=
            VK_SUCCESS ||
        (r = make_pipeline(g, janas_spv_q6k_matvec,
                           sizeof(janas_spv_q6k_matvec), &g->sm6, &g->pipe6)) !=
            VK_SUCCESS ||
        (r = make_pipeline(g, janas_spv_expert_act,
                           sizeof(janas_spv_expert_act), &g->sma, &g->pipea)) !=
            VK_SUCCESS) {
        set_err(err, err_len, "cannot create the shaders", r);
        goto fail;
    }
    VkCommandPoolCreateInfo cpci = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
        .flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,
        .queueFamilyIndex = family};
    VkCommandBufferAllocateInfo cba = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = 1};
    VkFenceCreateInfo fci = {.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    if (g->vkCreateCommandPool(g->dev, &cpci, NULL, &g->cp) != VK_SUCCESS ||
        (cba.commandPool = g->cp,
         g->vkAllocateCommandBuffers(g->dev, &cba, &g->cb) != VK_SUCCESS) ||
        g->vkCreateFence(g->dev, &fci, NULL, &g->fence) != VK_SUCCESS ||
        make_stage(g, &g->xs, X_STAGE_BYTES, !getenv("JANAS_GPU_XCOH")) != 0 ||
        make_stage(g, &g->ys, Y_STAGE_BYTES, 1) != 0) {
        snprintf(err, err_len, "cannot create the GPU buffers");
        goto fail;
    }
    pthread_mutex_init(&g->qlock, NULL);
    const char *ka = getenv("JANAS_GPU_KEEPALIVE_US");
    g->keep_us = ka ? (unsigned)atoi(ka) : 500;
    atomic_init(&g->ka_wanted, ka != NULL); /* as before when forced */
    if (g->keep_us > 0 && record_keep_alive(g) == 0 &&
        pthread_create(&g->ka, NULL, keep_alive, g) == 0)
        g->ka_running = 1;
    const char *e = getenv("JANAS_GPU_MIN_N");
    g->min_n = e && atoi(e) > 0 ? (size_t)atoi(e) : 2;
    e = getenv("JANAS_GPU_FULL_N");
    g->full_n = e && atoi(e) > 0 ? (size_t)atoi(e) : (size_t)-1;
    e = getenv("JANAS_GPU_VERBOSE");
    g->verbose = e && atoi(e) > 0;
    g->nospin = getenv("JANAS_GPU_NOSPIN") != NULL;
    g->block_wait = getenv("JANAS_GPU_BLOCKWAIT") != NULL;
    return g;

missing:
    snprintf(err, err_len, "incomplete Vulkan driver");
fail:
    janas_gpu_destroy(g);
    return NULL;
}

void janas_gpu_destroy(struct janas_gpu *g)
{
    if (!g)
        return;
    if (g->verbose)
        fprintf(stderr, "gpu begin: convert %.3f s, submit %.3f s\n", g->t_conv,
                g->t_sub);
    for (int i = 0; g->verbose && i < SHARE_SLOTS; i++)
        if (g->share[i].calls)
            fprintf(
                stderr,
                "gpu share: key %016llx, %u calls, GPU late in %u, "
                "share %.2f (mean %.2f); us/call: begin %.0f cpu %.0f "
                "wait %.0f copy %.0f\n",
                (unsigned long long)g->share[i].key, g->share[i].calls,
                g->share[i].waits, g->share[i].f,
                (double)g->share[i].rows_gpu /
                    (double)(g->share[i].rows_all ? g->share[i].rows_all : 1),
                1e6 * g->share[i].t_begin / g->share[i].calls,
                1e6 * g->share[i].t_cpu / g->share[i].calls,
                1e6 * g->share[i].t_wait / g->share[i].calls,
                1e6 * g->share[i].t_copy / g->share[i].calls);
    if (g->ka_running) {
        atomic_store(&g->ka_stop, 1);
        pthread_join(g->ka, NULL);
    }
    if (g->dev) {
        if (g->ka_fence)
            g->vkDestroyFence(g->dev, g->ka_fence, NULL);
        if (g->busy) {
            int waited;
            janas_gpu_finish(g, &waited);
        }
        struct stage *st[2] = {&g->xs, &g->ys};
        for (int i = 0; i < 2; i++) {
            if (st[i]->buf)
                g->vkDestroyBuffer(g->dev, st[i]->buf, NULL);
            if (st[i]->mem)
                g->vkFreeMemory(g->dev, st[i]->mem, NULL);
        }
        for (int i = 0; i < g->n_reg; i++) {
            g->vkDestroyBuffer(g->dev, g->reg[i].buf, NULL);
            g->vkFreeMemory(g->dev, g->reg[i].mem, NULL);
        }
        if (g->fence)
            g->vkDestroyFence(g->dev, g->fence, NULL);
        if (g->cp)
            g->vkDestroyCommandPool(g->dev, g->cp, NULL);
        if (g->pipe)
            g->vkDestroyPipeline(g->dev, g->pipe, NULL);
        if (g->pipe6)
            g->vkDestroyPipeline(g->dev, g->pipe6, NULL);
        if (g->pipea)
            g->vkDestroyPipeline(g->dev, g->pipea, NULL);
        if (g->sma)
            g->vkDestroyShaderModule(g->dev, g->sma, NULL);
        if (g->sm6)
            g->vkDestroyShaderModule(g->dev, g->sm6, NULL);
        if (g->pl)
            g->vkDestroyPipelineLayout(g->dev, g->pl, NULL);
        if (g->sm)
            g->vkDestroyShaderModule(g->dev, g->sm, NULL);
        g->vkDestroyDevice(g->dev, NULL);
    }
    if (g->inst && g->vkDestroyInstance)
        g->vkDestroyInstance(g->inst, NULL);
    if (g->lib)
        dlclose(g->lib);
    free(g);
}

const char *janas_gpu_name(const struct janas_gpu *g)
{
    return g->name;
}

unsigned janas_gpu_subgroup(const struct janas_gpu *g)
{
    return g->sg;
}

void janas_gpu_keep_awake(struct janas_gpu *g, int on)
{
    if (g)
        atomic_store(&g->ka_wanted, on);
}

/* A memory type local to the device, preferably not visible to the host
   (the fastest memory of a discrete GPU). */
static int local_type(const struct janas_gpu *g, uint32_t bits)
{
    int any = -1;
    for (uint32_t i = 0; i < g->mp.memoryTypeCount; i++) {
        VkMemoryPropertyFlags f = g->mp.memoryTypes[i].propertyFlags;
        if (!(bits & (1u << i)) || !(f & VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT))
            continue;
        if (!(f & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT))
            return (int)i;
        if (any < 0)
            any = (int)i;
    }
    return any;
}

/*
 * A copy of host memory in the device's own memory, for a discrete GPU:
 * uploaded once through a staging buffer, in chunks. The CPU keeps its own
 * copy; the region maps the host range to the device copy.
 */
static int copy_to_device(struct janas_gpu *g, const void *p, size_t bytes)
{
    struct region *rg = &g->reg[g->n_reg];
    VkBufferCreateInfo bi = {.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                             .size = bytes,
                             .usage =
                                 VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                 VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT |
                                 VK_BUFFER_USAGE_TRANSFER_DST_BIT};
    if (g->vkCreateBuffer(g->dev, &bi, NULL, &rg->buf) != VK_SUCCESS)
        return -1;
    VkMemoryRequirements req;
    g->vkGetBufferMemoryRequirements(g->dev, rg->buf, &req);
    int t = local_type(g, req.memoryTypeBits);
    /* room in its heap: the rest of the engine runs on the CPU otherwise */
    if (t < 0 || g->mp.memoryHeaps[g->mp.memoryTypes[t].heapIndex].size <
                     req.size + ((VkDeviceSize)512 << 20)) {
        g->vkDestroyBuffer(g->dev, rg->buf, NULL);
        return -1;
    }
    VkMemoryAllocateFlagsInfo fl = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO,
        .flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT};
    VkMemoryAllocateInfo ai = {.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                               .pNext = &fl,
                               .allocationSize = req.size,
                               .memoryTypeIndex = (uint32_t)t};
    if (g->vkAllocateMemory(g->dev, &ai, NULL, &rg->mem) != VK_SUCCESS) {
        g->vkDestroyBuffer(g->dev, rg->buf, NULL);
        return -1;
    }
    if (g->vkBindBufferMemory(g->dev, rg->buf, rg->mem, 0) != VK_SUCCESS)
        goto fail;
    /* staging: 64 MiB of host memory, one chunk at a time */
    struct stage st = {0};
    size_t chunk = (size_t)64 << 20;
    VkBufferCreateInfo sbi = {.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                              .size = chunk,
                              .usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT};
    if (g->vkCreateBuffer(g->dev, &sbi, NULL, &st.buf) != VK_SUCCESS)
        goto fail;
    g->vkGetBufferMemoryRequirements(g->dev, st.buf, &req);
    int ts = mem_type(g, req.memoryTypeBits,
                      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                          VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    VkMemoryAllocateInfo sai = {.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                                .allocationSize = req.size,
                                .memoryTypeIndex = (uint32_t)ts};
    int ok = ts >= 0 &&
             g->vkAllocateMemory(g->dev, &sai, NULL, &st.mem) == VK_SUCCESS &&
             g->vkBindBufferMemory(g->dev, st.buf, st.mem, 0) == VK_SUCCESS &&
             g->vkMapMemory(g->dev, st.mem, 0, VK_WHOLE_SIZE, 0,
                            (void **)&st.map) == VK_SUCCESS;
    for (size_t off = 0; ok && off < bytes; off += chunk) {
        size_t nb = bytes - off < chunk ? bytes - off : chunk;
        memcpy(st.map, (const uint8_t *)p + off, nb);
        VkCommandBufferBeginInfo bb = {
            .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
            .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT};
        VkBufferCopy cp = {.srcOffset = 0, .dstOffset = off, .size = nb};
        VkSubmitInfo sub = {.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
                            .commandBufferCount = 1,
                            .pCommandBuffers = &g->cb};
        ok = g->vkResetCommandBuffer(g->cb, 0) == VK_SUCCESS &&
             g->vkBeginCommandBuffer(g->cb, &bb) == VK_SUCCESS;
        if (ok)
            g->vkCmdCopyBuffer(g->cb, st.buf, rg->buf, 1, &cp);
        ok = ok && g->vkEndCommandBuffer(g->cb) == VK_SUCCESS;
        pthread_mutex_lock(&g->qlock);
        ok = ok && g->vkQueueSubmit(g->queue, 1, &sub, g->fence) == VK_SUCCESS;
        pthread_mutex_unlock(&g->qlock);
        ok = ok && g->vkWaitForFences(g->dev, 1, &g->fence, VK_TRUE,
                                      UINT64_MAX) == VK_SUCCESS;
        g->vkResetFences(g->dev, 1, &g->fence);
    }
    if (st.buf)
        g->vkDestroyBuffer(g->dev, st.buf, NULL);
    if (st.mem)
        g->vkFreeMemory(g->dev, st.mem, NULL);
    if (!ok)
        goto fail;
    rg->host = p;
    rg->bytes = bytes;
    rg->addr = buffer_address(g, rg->buf);
    rg->coherent = 1;
    g->n_reg++;
    return 0;

fail:
    g->vkDestroyBuffer(g->dev, rg->buf, NULL);
    g->vkFreeMemory(g->dev, rg->mem, NULL);
    return -1;
}

int janas_gpu_import(struct janas_gpu *g, const void *p, size_t bytes)
{
    if (g->n_reg == MAX_REGIONS || ((uintptr_t)p | bytes) % 4096 != 0 ||
        bytes == 0 || bytes > ((size_t)4 << 30))
        return -1;
    /* a discrete GPU (or JANAS_GPU_COPY=1, to test that path) reads a copy
       in its own memory */
    if (g->discrete || !g->host_import || getenv("JANAS_GPU_COPY"))
        return copy_to_device(g, p, bytes);
    struct region *rg = &g->reg[g->n_reg];
    VkMemoryHostPointerPropertiesEXT hp = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_HOST_POINTER_PROPERTIES_EXT};
    if (g->vkGetMemoryHostPointerPropertiesEXT(
            g->dev, VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT, p,
            &hp) != VK_SUCCESS)
        return -1;
    VkExternalMemoryBufferCreateInfo eb = {
        .sType = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO,
        .handleTypes = VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT};
    VkBufferCreateInfo bi = {.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                             .pNext = &eb,
                             .size = bytes,
                             .usage =
                                 VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                 VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT};
    if (g->vkCreateBuffer(g->dev, &bi, NULL, &rg->buf) != VK_SUCCESS)
        return -1;
    VkMemoryRequirements req;
    g->vkGetBufferMemoryRequirements(g->dev, rg->buf, &req);
    int t = mem_type(g, hp.memoryTypeBits & req.memoryTypeBits, 0);
    VkImportMemoryHostPointerInfoEXT imp = {
        .sType = VK_STRUCTURE_TYPE_IMPORT_MEMORY_HOST_POINTER_INFO_EXT,
        .handleType = VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT,
        .pHostPointer = (void *)p};
    VkMemoryAllocateFlagsInfo fl = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO,
        .pNext = &imp,
        .flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT};
    VkMemoryAllocateInfo ai = {.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                               .pNext = &fl,
                               .allocationSize = bytes,
                               .memoryTypeIndex = (uint32_t)t};
    if (t < 0 ||
        g->vkAllocateMemory(g->dev, &ai, NULL, &rg->mem) != VK_SUCCESS) {
        g->vkDestroyBuffer(g->dev, rg->buf, NULL);
        return -1;
    }
    if (g->vkBindBufferMemory(g->dev, rg->buf, rg->mem, 0) != VK_SUCCESS) {
        g->vkDestroyBuffer(g->dev, rg->buf, NULL);
        g->vkFreeMemory(g->dev, rg->mem, NULL);
        return -1;
    }
    rg->host = p;
    rg->bytes = bytes;
    rg->addr = buffer_address(g, rg->buf);
    rg->coherent = 1;
    g->n_reg++;
    return 0;
}

void *janas_gpu_alloc(struct janas_gpu *g, size_t bytes)
{
    bytes = (bytes + 4095) / 4096 * 4096;
    if (g->n_reg == MAX_REGIONS || bytes == 0 || bytes > ((size_t)4 << 30))
        return NULL;
    struct region *rg = &g->reg[g->n_reg];
    VkBufferCreateInfo bi = {.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                             .size = bytes,
                             .usage =
                                 VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                 VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT};
    if (g->vkCreateBuffer(g->dev, &bi, NULL, &rg->buf) != VK_SUCCESS)
        return NULL;
    VkMemoryRequirements req;
    g->vkGetBufferMemoryRequirements(g->dev, rg->buf, &req);
    int t = mem_type(g, req.memoryTypeBits,
                     VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                         VK_MEMORY_PROPERTY_HOST_CACHED_BIT);
    VkMemoryAllocateFlagsInfo fl = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO,
        .flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT};
    VkMemoryAllocateInfo ai = {.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                               .pNext = &fl,
                               .allocationSize = req.size,
                               .memoryTypeIndex = (uint32_t)t};
    void *p = NULL;
    if (t < 0 ||
        g->vkAllocateMemory(g->dev, &ai, NULL, &rg->mem) != VK_SUCCESS) {
        g->vkDestroyBuffer(g->dev, rg->buf, NULL);
        return NULL;
    }
    if (g->vkBindBufferMemory(g->dev, rg->buf, rg->mem, 0) != VK_SUCCESS ||
        g->vkMapMemory(g->dev, rg->mem, 0, VK_WHOLE_SIZE, 0, &p) !=
            VK_SUCCESS) {
        g->vkDestroyBuffer(g->dev, rg->buf, NULL);
        g->vkFreeMemory(g->dev, rg->mem, NULL);
        return NULL;
    }
    rg->host = p;
    rg->bytes = bytes;
    rg->addr = buffer_address(g, rg->buf);
    rg->coherent = (g->mp.memoryTypes[t].propertyFlags &
                    VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) != 0;
    g->n_reg++;
    return p;
}

void janas_gpu_flush(struct janas_gpu *g, const void *p, size_t bytes)
{
    const uint8_t *b = p;
    for (int i = 0; i < g->n_reg; i++) {
        const struct region *rg = &g->reg[i];
        if (b < rg->host || b + bytes > rg->host + rg->bytes || rg->coherent)
            continue;
        VkDeviceSize off = (VkDeviceSize)(b - rg->host) / g->atom * g->atom;
        VkDeviceSize end = (VkDeviceSize)(b + bytes - rg->host);
        end = (end + g->atom - 1) / g->atom * g->atom;
        VkMappedMemoryRange mr = {
            .sType = VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE,
            .memory = rg->mem,
            .offset = off,
            .size = end >= rg->bytes ? VK_WHOLE_SIZE : end - off};
        g->vkFlushMappedMemoryRanges(g->dev, 1, &mr);
    }
}

/* The region holding [p, p + bytes), or NULL. */
static const struct region *find_region(const struct janas_gpu *g,
                                        const void *p, size_t bytes)
{
    const uint8_t *b = p;
    for (int i = 0; i < g->n_reg; i++)
        if (b >= g->reg[i].host &&
            b + bytes <= g->reg[i].host + g->reg[i].bytes)
            return &g->reg[i];
    return NULL;
}

/* Bytes the shader may read for rows of a task: Q6_K reads up to 2 bytes
   past the last block (whole words). */
static size_t read_bytes(const struct janas_matvec_task *t, size_t rows)
{
    size_t nb = t->cols / JANAS_QK;
    return rows * nb * janas_qtype_block_size(t->type) +
           (t->type == JANAS_Q6_K ? 4 : 0);
}

int janas_gpu_can(const struct janas_gpu *g, const struct janas_matvec_task *t)
{
    size_t nb = t->cols / JANAS_QK, nv = t->n_vec ? t->n_vec : 1;
    int typed = (t->type == JANAS_Q4_K && (uintptr_t)t->w % 16 == 0) ||
                (t->type == JANAS_Q6_K && (uintptr_t)t->w % 4 == 0);
    return !g->broken && typed && t->cols % JANAS_QK == 0 &&
           nv * nb * GPU_BLOCK <= X_STAGE_BYTES &&
           t->rows * nv * sizeof(float) <= Y_STAGE_BYTES &&
           find_region(g, t->w, read_bytes(t, t->rows));
}

/* Copies nv vectors of nb Q8_K blocks into the shader's layout. */
static void convert_x(uint8_t *dst, const struct janas_block_q8k *x, size_t xs,
                      size_t nv, size_t nb)
{
    _Alignas(64) uint8_t blk[GPU_BLOCK] = {0};
    for (size_t v = 0; v < nv; v++)
        for (size_t b = 0; b < nb; b++, dst += GPU_BLOCK) {
            const struct janas_block_q8k *s = x + v * xs + b;
            memcpy(blk, s->qs, JANAS_QK);
            memcpy(blk + JANAS_QK, s->bsums, sizeof(s->bsums));
            memcpy(blk + JANAS_QK + sizeof(s->bsums), &s->d, sizeof(float));
            memcpy(dst, blk, GPU_BLOCK);
        }
}

int janas_gpu_begin(struct janas_gpu *g, const struct janas_matvec_task *tasks,
                    const size_t *gpu_rows, size_t n)
{
    if (g->busy || g->broken)
        return -1;
    /* activations: tasks of a group often share theirs, converted once */
    struct {
        const void *x;
        size_t nv, xs, nb, off;
    } xc[MAX_XCACHE];
    size_t n_xc = 0, x_used = 0, y_used = 0;
    g->n_pend = 0;
    if (g->vkResetCommandBuffer(g->cb, 0) != VK_SUCCESS)
        return -1;
    VkCommandBufferBeginInfo bb = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
        .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT};
    if (g->vkBeginCommandBuffer(g->cb, &bb) != VK_SUCCESS)
        return -1;
    VkPipeline bound = VK_NULL_HANDLE;
    for (size_t i = 0; i < n; i++) {
        if (gpu_rows[i] == 0)
            continue;
        const struct janas_matvec_task *t = &tasks[i];
        VkPipeline want = t->type == JANAS_Q6_K ? g->pipe6 : g->pipe;
        if (want != bound) {
            g->vkCmdBindPipeline(g->cb, VK_PIPELINE_BIND_POINT_COMPUTE, want);
            bound = want;
        }
        size_t nb = t->cols / JANAS_QK, nv = t->n_vec ? t->n_vec : 1;
        size_t xs = t->x_stride ? t->x_stride : nb;
        size_t k = 0;
        while (k < n_xc && !(xc[k].x == t->x && xc[k].nv == nv &&
                             xc[k].xs == xs && xc[k].nb == nb))
            k++;
        if (k == n_xc) {
            size_t bytes = nv * nb * GPU_BLOCK;
            if (n_xc == MAX_XCACHE || x_used + bytes > X_STAGE_BYTES)
                return -1;
            double tc = g->verbose ? now() : 0;
            convert_x(g->xs.map + x_used, t->x, xs, nv, nb);
            if (g->verbose)
                g->t_conv += now() - tc;
            xc[k].x = t->x;
            xc[k].nv = nv;
            xc[k].xs = xs;
            xc[k].nb = nb;
            xc[k].off = x_used;
            x_used += bytes;
            n_xc++;
        }
        size_t ybytes = gpu_rows[i] * nv * sizeof(float);
        const struct region *rg =
            find_region(g, t->w, read_bytes(t, gpu_rows[i]));
        if (!rg || g->n_pend == MAX_PENDING || y_used + ybytes > Y_STAGE_BYTES)
            return -1;
        VkDeviceAddress wa =
            rg->addr + (VkDeviceAddress)((const uint8_t *)t->w - rg->host);
        VkDeviceAddress xa = g->xs.addr + xc[k].off, ya = g->ys.addr + y_used;
        struct push pc = {.w = {(uint32_t)wa, (uint32_t)(wa >> 32)},
                          .x = {(uint32_t)xa, (uint32_t)(xa >> 32)},
                          .y = {(uint32_t)ya, (uint32_t)(ya >> 32)},
                          .rows = (uint32_t)gpu_rows[i],
                          .nb = (uint32_t)nb,
                          .nv = (uint32_t)nv,
                          .xs = (uint32_t)nb,
                          .ys = (uint32_t)gpu_rows[i]};
        g->vkCmdPushConstants(g->cb, g->pl, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                              sizeof(pc), &pc);
        g->vkCmdDispatch(
            g->cb,
            (uint32_t)((gpu_rows[i] + ROWS_PER_GROUP - 1) / ROWS_PER_GROUP),
            (uint32_t)((nv + NV_PER_GROUP - 1) / NV_PER_GROUP), 1);
        g->pend[g->n_pend++] =
            (struct pending){.y = t->y,
                             .rows = gpu_rows[i],
                             .nv = nv,
                             .y_stride = t->y_stride ? t->y_stride : t->rows,
                             .off = y_used};
        y_used += ybytes;
    }
    /* the shader's writes made visible to the host once the fence signals
       (without this they can stay in the GPU's cache) */
    VkMemoryBarrier mb = {.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER,
                          .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
                          .dstAccessMask = VK_ACCESS_HOST_READ_BIT};
    g->vkCmdPipelineBarrier(g->cb, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                            VK_PIPELINE_STAGE_HOST_BIT, 0, 1, &mb, 0, NULL, 0,
                            NULL);
    if (g->vkEndCommandBuffer(g->cb) != VK_SUCCESS)
        return -1;
    g->y_used = y_used;
    if (g->n_pend == 0)
        return 0;
    if (!g->xs.coherent && x_used > 0) {
        VkDeviceSize sz = (x_used + g->atom - 1) / g->atom * g->atom;
        VkMappedMemoryRange mr = {
            .sType = VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE,
            .memory = g->xs.mem,
            .size = sz < g->xs.bytes ? sz : VK_WHOLE_SIZE};
        g->vkFlushMappedMemoryRanges(g->dev, 1, &mr);
    }
    VkSubmitInfo sub = {.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
                        .commandBufferCount = 1,
                        .pCommandBuffers = &g->cb};
    double ts = g->verbose ? now() : 0;
    pthread_mutex_lock(&g->qlock);
    VkResult sr = g->vkQueueSubmit(g->queue, 1, &sub, g->fence);
    pthread_mutex_unlock(&g->qlock);
    if (g->verbose)
        g->t_sub += now() - ts;
    if (sr != VK_SUCCESS) {
        g->broken = 1;
        return -1;
    }
    g->busy = 1;
    return 0;
}

/* Push constants of the activation shader. */
struct push_act {
    uint32_t g[2], u[2], x[2];
    uint32_t blocks;
};

static void push_addr(uint32_t out[2], VkDeviceAddress a)
{
    out[0] = (uint32_t)a;
    out[1] = (uint32_t)(a >> 32);
}

/* A product of one weight matrix (rows x cols of type) with one vector. */
static int record_product(struct janas_gpu *g, VkPipeline *bound, int type,
                          const void *w, size_t rows, size_t cols,
                          VkDeviceAddress xa, VkDeviceAddress ya)
{
    struct janas_matvec_task t = {
        .type = type, .w = w, .rows = rows, .cols = cols, .n_vec = 1};
    const struct region *rg = find_region(g, w, read_bytes(&t, rows));
    if (!rg || (type != JANAS_Q4_K && type != JANAS_Q6_K))
        return -1;
    VkPipeline want = type == JANAS_Q6_K ? g->pipe6 : g->pipe;
    if (want != *bound) {
        g->vkCmdBindPipeline(g->cb, VK_PIPELINE_BIND_POINT_COMPUTE, want);
        *bound = want;
    }
    VkDeviceAddress wa =
        rg->addr + (VkDeviceAddress)((const uint8_t *)w - rg->host);
    size_t nb = cols / JANAS_QK;
    struct push pc = {.rows = (uint32_t)rows,
                      .nb = (uint32_t)nb,
                      .nv = 1,
                      .xs = (uint32_t)nb,
                      .ys = (uint32_t)rows};
    push_addr(pc.w, wa);
    push_addr(pc.x, xa);
    push_addr(pc.y, ya);
    g->vkCmdPushConstants(g->cb, g->pl, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                          sizeof(pc), &pc);
    g->vkCmdDispatch(
        g->cb, (uint32_t)((rows + ROWS_PER_GROUP - 1) / ROWS_PER_GROUP), 1, 1);
    return 0;
}

static void compute_barrier(struct janas_gpu *g)
{
    VkMemoryBarrier mb = {.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER,
                          .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
                          .dstAccessMask = VK_ACCESS_SHADER_READ_BIT};
    g->vkCmdPipelineBarrier(g->cb, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0,
                            NULL, 0, NULL);
}

int janas_gpu_ffn_begin(struct janas_gpu *g, const struct janas_gpu_expert *e,
                        size_t n, const struct janas_block_q8k *x, size_t d,
                        size_t ff, float *out)
{
    if (g->busy || g->broken || n == 0 || d % JANAS_QK || ff % JANAS_QK)
        return -1;
    size_t nbx = d / JANAS_QK, nbh = ff / JANAS_QK;
    /* X stage: x, then every expert's h; Y stage: gate, up, down */
    size_t hoff = (nbx * GPU_BLOCK + 255) / 256 * 256;
    size_t up_off = n * ff * sizeof(float), down_off = 2 * up_off;
    if (hoff + n * nbh * GPU_BLOCK > X_STAGE_BYTES ||
        down_off + n * d * sizeof(float) > Y_STAGE_BYTES)
        return -1;
    convert_x(g->xs.map, x, nbx, 1, nbx);
    if (g->vkResetCommandBuffer(g->cb, 0) != VK_SUCCESS)
        return -1;
    VkCommandBufferBeginInfo bb = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
        .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT};
    if (g->vkBeginCommandBuffer(g->cb, &bb) != VK_SUCCESS)
        return -1;
    VkPipeline bound = VK_NULL_HANDLE;
    VkDeviceAddress X = g->xs.addr, Y = g->ys.addr;
    for (size_t i = 0; i < n; i++)
        if (record_product(g, &bound, e[i].gate_type, e[i].gate, ff, d, X,
                           Y + i * ff * sizeof(float)) != 0 ||
            record_product(g, &bound, e[i].up_type, e[i].up, ff, d, X,
                           Y + up_off + i * ff * sizeof(float)) != 0)
            return -1;
    compute_barrier(g);
    g->vkCmdBindPipeline(g->cb, VK_PIPELINE_BIND_POINT_COMPUTE, g->pipea);
    bound = g->pipea;
    struct push_act pa = {.blocks = (uint32_t)(n * nbh)};
    push_addr(pa.g, Y);
    push_addr(pa.u, Y + up_off);
    push_addr(pa.x, X + hoff);
    g->vkCmdPushConstants(g->cb, g->pl, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                          sizeof(pa), &pa);
    g->vkCmdDispatch(g->cb, (uint32_t)(n * nbh), 1, 1);
    compute_barrier(g);
    for (size_t i = 0; i < n; i++)
        if (record_product(g, &bound, e[i].down_type, e[i].down, d, ff,
                           X + hoff + i * nbh * GPU_BLOCK,
                           Y + down_off + i * d * sizeof(float)) != 0)
            return -1;
    VkMemoryBarrier mb = {.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER,
                          .srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT,
                          .dstAccessMask = VK_ACCESS_HOST_READ_BIT};
    g->vkCmdPipelineBarrier(g->cb, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                            VK_PIPELINE_STAGE_HOST_BIT, 0, 1, &mb, 0, NULL, 0,
                            NULL);
    if (g->vkEndCommandBuffer(g->cb) != VK_SUCCESS)
        return -1;
    if (!g->xs.coherent) {
        VkMappedMemoryRange mr = {
            .sType = VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE,
            .memory = g->xs.mem,
            .size = (hoff + g->atom - 1) / g->atom * g->atom};
        g->vkFlushMappedMemoryRanges(g->dev, 1, &mr);
    }
    g->n_pend = 1;
    g->pend[0] = (struct pending){
        .y = out, .rows = n * d, .nv = 1, .y_stride = n * d, .off = down_off};
    g->y_used = down_off + n * d * sizeof(float);
    VkSubmitInfo sub = {.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
                        .commandBufferCount = 1,
                        .pCommandBuffers = &g->cb};
    pthread_mutex_lock(&g->qlock);
    VkResult sr = g->vkQueueSubmit(g->queue, 1, &sub, g->fence);
    pthread_mutex_unlock(&g->qlock);
    if (sr != VK_SUCCESS) {
        g->broken = 1;
        g->n_pend = 0;
        return -1;
    }
    g->busy = 1;
    return 0;
}

int janas_gpu_finish(struct janas_gpu *g, int *waited)
{
    *waited = 0;
    if (!g->busy)
        return g->n_pend ? -1 : 0;
    VkResult r;
    /* the CPU's share is done: wait actively, the reply comes sooner */
    double t0 = g->verbose ? now() : 0;
    if (g->block_wait) {
        /* a blocking wait: the driver raises the GPU's clock for waiters */
        if ((r = g->vkGetFenceStatus(g->dev, g->fence)) == VK_NOT_READY) {
            *waited = 1;
            r = g->vkWaitForFences(g->dev, 1, &g->fence, VK_TRUE, UINT64_MAX);
        }
    } else {
        while ((r = g->vkGetFenceStatus(g->dev, g->fence)) == VK_NOT_READY) {
            *waited = 1;
            _mm_pause();
        }
    }
    g->t_waited = g->verbose ? now() - t0 : 0;
    g->busy = 0;
    if (r != VK_SUCCESS) {
        g->broken = 1; /* device lost: the caller computes these rows */
        return -1;
    }
    g->vkResetFences(g->dev, 1, &g->fence);
    if (!g->ys.coherent) {
        /* only the bytes written: invalidating costs per cache line */
        VkDeviceSize sz = (g->y_used + g->atom - 1) / g->atom * g->atom;
        VkMappedMemoryRange mr = {
            .sType = VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE,
            .memory = g->ys.mem,
            .size = sz < g->ys.bytes ? sz : VK_WHOLE_SIZE};
        g->vkInvalidateMappedMemoryRanges(g->dev, 1, &mr);
    }
    for (size_t i = 0; i < g->n_pend; i++) {
        const struct pending *p = &g->pend[i];
        const float *src = (const float *)(g->ys.map + p->off);
        for (size_t v = 0; v < p->nv; v++)
            memcpy(p->y + v * p->y_stride, src + v * p->rows,
                   p->rows * sizeof(float));
    }
    g->n_pend = 0;
    return 0;
}

static struct share *find_share(struct janas_gpu *g, uint64_t key)
{
    size_t i = (size_t)(key * 0x9e3779b97f4a7c15ull >> 58) % SHARE_SLOTS;
    for (size_t k = 0; k < SHARE_SLOTS; k++, i = (i + 1) % SHARE_SLOTS) {
        if (g->share[i].key == key)
            return &g->share[i];
        if (g->share[i].calls == 0) {
            g->share[i] = (struct share){.key = key, .f = 0.4f};
            return &g->share[i];
        }
    }
    return NULL;
}

void janas_gpu_matvec_group(struct janas_gpu *g, struct janas_pool *pool,
                            const struct janas_matvec_task *tasks, size_t n)
{
    size_t nv = tasks[0].n_vec ? tasks[0].n_vec : 1;
    if (!g || g->broken || nv < g->min_n || n > MAX_GROUP) {
        janas_matvec_q4k_group(pool, tasks, n);
        return;
    }
    uint64_t key = (uint64_t)n << 48 ^ (uint64_t)tasks[0].rows << 24 ^
                   (uint64_t)tasks[0].cols << 8 ^ nv;
    struct share *sh = find_share(g, key);
    if (sh && sh->off > 0) {
        /* the GPU was late even with the smallest share: CPU for a while */
        sh->off--;
        janas_matvec_q4k_group(pool, tasks, n);
        return;
    }
    size_t gpu_rows[MAX_GROUP], any = 0;
    struct janas_matvec_task cpu[MAX_GROUP];
    for (size_t i = 0; i < n; i++) {
        const struct janas_matvec_task *t = &tasks[i];
        size_t r = 0;
        if (nv >= g->full_n && janas_gpu_can(g, t)) {
            r = t->rows; /* the GPU alone */
        } else if (sh && t->rows >= 2 * ROWS_PER_GROUP && janas_gpu_can(g, t)) {
            r = (size_t)(sh->f * (float)t->rows) / ROWS_PER_GROUP *
                ROWS_PER_GROUP;
            if (r > t->rows)
                r = t->rows;
        }
        gpu_rows[i] = r;
        any += r;
        size_t nb = t->cols / JANAS_QK;
        cpu[i] = *t;
        cpu[i].w =
            (const uint8_t *)t->w + r * nb * janas_qtype_block_size(t->type);
        cpu[i].y = t->y + r;
        cpu[i].rows = t->rows - r;
        cpu[i].y_stride = t->y_stride ? t->y_stride : t->rows;
    }
    double t0 = g->verbose ? now() : 0;
    /* experiment: the pool's idle workers asleep while submitting */
    int spin = janas_pool_get_spin(pool);
    if (g->nospin)
        janas_pool_set_spin(pool, 0);
    int rb = any == 0 ? -1 : janas_gpu_begin(g, tasks, gpu_rows, n);
    if (g->nospin)
        janas_pool_set_spin(pool, spin);
    if (rb != 0) {
        janas_matvec_q4k_group(pool, tasks, n);
        return;
    }
    /* the pool's share meanwhile (tasks left with no rows skipped) */
    double t1 = g->verbose ? now() : 0;
    size_t m = 0, all = 0;
    for (size_t i = 0; i < n; i++) {
        all += tasks[i].rows;
        if (cpu[i].rows > 0)
            cpu[m++] = cpu[i];
    }
    if (m > 0)
        janas_matvec_q4k_group(pool, cpu, m);
    double t2 = g->verbose ? now() : 0;
    int waited;
    if (janas_gpu_finish(g, &waited) != 0) {
        /* the GPU failed: its rows on the CPU, and no GPU from now on */
        for (size_t i = 0; i < n; i++) {
            cpu[i] = tasks[i];
            cpu[i].rows = gpu_rows[i];
            cpu[i].y_stride =
                tasks[i].y_stride ? tasks[i].y_stride : tasks[i].rows;
        }
        janas_matvec_q4k_group(pool, cpu, n);
        return;
    }
    if (nv >= g->full_n) {
        if (g->verbose && sh) {
            sh->calls++;
            sh->waits += (uint32_t)waited;
            sh->t_begin += t1 - t0;
            sh->t_cpu += t2 - t1;
            sh->t_wait += g->t_waited;
            sh->t_copy += now() - t2 - g->t_waited;
            sh->rows_gpu += any;
            sh->rows_all += all;
        }
        return;
    }
    if (g->verbose) {
        sh->t_begin += t1 - t0;
        sh->t_cpu += t2 - t1;
        sh->t_wait += g->t_waited;
        sh->t_copy += now() - t2 - g->t_waited;
        sh->rows_gpu += any;
        sh->rows_all += all;
    }
    /* late GPU: less next time; early: more */
    sh->calls++;
    sh->waits += (uint32_t)waited;
    if (waited && sh->f <= 0.05f) {
        sh->off = 256; /* not worth it for this shape: retry later */
        return;
    }
    sh->f = waited ? sh->f * 0.95f : sh->f * 1.05f;
    if (sh->f > 0.95f)
        sh->f = 0.95f;
    if (sh->f < 0.05f)
        sh->f = 0.05f;
}

#else /* no GPU in this build */

struct janas_gpu {
    int unused;
};

struct janas_gpu *janas_gpu_create(char *err, size_t err_len)
{
    snprintf(err, err_len, "built without GPU support");
    return NULL;
}

void janas_gpu_destroy(struct janas_gpu *g)
{
    (void)g;
}

int janas_gpu_import(struct janas_gpu *g, const void *p, size_t bytes)
{
    (void)g;
    (void)p;
    (void)bytes;
    return -1;
}

void *janas_gpu_alloc(struct janas_gpu *g, size_t bytes)
{
    (void)g;
    (void)bytes;
    return NULL;
}

void janas_gpu_flush(struct janas_gpu *g, const void *p, size_t bytes)
{
    (void)g;
    (void)p;
    (void)bytes;
}

int janas_gpu_can(const struct janas_gpu *g, const struct janas_matvec_task *t)
{
    (void)g;
    (void)t;
    return 0;
}

int janas_gpu_begin(struct janas_gpu *g, const struct janas_matvec_task *tasks,
                    const size_t *gpu_rows, size_t n)
{
    (void)g;
    (void)tasks;
    (void)gpu_rows;
    (void)n;
    return -1;
}

int janas_gpu_finish(struct janas_gpu *g, int *waited)
{
    (void)g;
    *waited = 0;
    return -1;
}

const char *janas_gpu_name(const struct janas_gpu *g)
{
    (void)g;
    return "";
}

unsigned janas_gpu_subgroup(const struct janas_gpu *g)
{
    (void)g;
    return 0;
}

void janas_gpu_matvec_group(struct janas_gpu *g, struct janas_pool *pool,
                            const struct janas_matvec_task *tasks, size_t n)
{
    (void)g;
    janas_matvec_q4k_group(pool, tasks, n);
}

void janas_gpu_keep_awake(struct janas_gpu *g, int on)
{
    (void)g;
    (void)on;
}

int janas_gpu_ffn_begin(struct janas_gpu *g, const struct janas_gpu_expert *e,
                        size_t n, const struct janas_block_q8k *x, size_t d,
                        size_t ff, float *out)
{
    (void)g;
    (void)e;
    (void)n;
    (void)x;
    (void)d;
    (void)ff;
    (void)out;
    return -1;
}

#endif
