/* SPDX-License-Identifier: GPL-3.0-or-later
   Copyright (C) 2026 Maurizio Cammalleri */
/*
 * geo.h - the geography of Janas's services (janas-flights, janas-weather):
 * airports, cities, seas, and a position
 * put into words ("over the Tyrrhenian Sea, between Corsica (France) and
 * Tuscany (Italy), 85 km WSW of Livorno"), so that the model telling it
 * never has to work out where a latitude and a longitude are.
 *
 * The tables are generated by tools/gen_geo.c into geo_data.h, from
 * OurAirports (public domain), GeoNames (CC BY 4.0) and Natural Earth
 * (public domain). Coordinates are in hundred-thousandths of a degree.
 */
#ifndef JANAS_COMMON_GEO_H
#define JANAS_COMMON_GEO_H

#include <stdint.h>

#include "llm/json.h"

struct geo_country {
    const char *iso2, *name;
};

struct geo_region { /* a first-level division: Tuscany, Corsica */
    uint16_t country;
    const char *name;
};

struct geo_city {
    int32_t lat, lon;
    uint32_t pop;
    uint16_t country, region, tz; /* region 0xFFFF: none known */
    const char *name, *ascii;
};

struct geo_airport {
    int32_t lat, lon;
    uint16_t country, tz;
    char iata[4], icao[5];
    const char *name, *city;
};

/* a sea: its rings (outer boundaries and holes alike: a point is in the
   sea when it is inside an odd number of them) */
struct geo_sea {
    const char *name;
    uint32_t ring0, n_rings;
    int32_t lat_min, lat_max, lon_min, lon_max;
};

struct geo_ring {
    uint32_t pt0, n; /* into the points, (lon, lat) pairs */
};

/* Great-circle distance in km, initial bearing in degrees (0 = north). */
double geo_km(double lat1, double lon1, double lat2, double lon2);
double geo_bearing(double lat1, double lon1, double lat2, double lon2);
/* "N", "NNE", ... for a bearing. */
const char *geo_compass(double deg);

/* An airport by IATA or ICAO code, or else by its city or name (ASCII,
   case ignored), or else the nearest to a city of that name (within 50
   km); NULL when none. */
const struct geo_airport *geo_airport_find(const char *what);
/* A city by name (its ASCII name, case ignored; the most populous of those
   of that name); NULL when none. */
const struct geo_city *geo_city_find(const char *name);
/* A first-level region by its English name or, for Italy's, its Italian
   one ("Liguria", "Sicilia", "Lombardy"): its most populous city of the
   tables, or NULL. Of two regions so called, the one of the larger city. */
const struct geo_city *geo_region_city(const char *name);
/* The nearest city (within 5 degrees of latitude; one under 10,000
   people only within 3 km), and its distance; NULL when none. */
const struct geo_city *geo_city_near(double lat, double lon, double *km);
/* The nearest airport with scheduled flights, and its distance. */
const struct geo_airport *geo_airport_near(double lat, double lon, double *km);

const char *geo_country_name(uint16_t i);
const char *geo_country_iso2(uint16_t i); /* "IT" */
const char *geo_region_name(uint16_t i);
const char *geo_tz_name(uint16_t i);

/* The name of the sea the point is over, or NULL (land, or a sea too
   small for the tables). */
const char *geo_sea_at(double lat, double lon);

/* A sea as an area to search: the polygons of that name, and the smaller
   seas, gulfs and straits with at least half of their box within theirs
   (Natural Earth cuts them out of the sea around them). The box is that
   of the sea's own polygons. */
struct geo_area {
    const char *name;
    int32_t lat_min, lat_max, lon_min, lon_max; /* its own polygons' box */
    int32_t s_lat_min, s_lat_max, s_lon_min, s_lon_max; /* with its parts */
};

/* A sea by its English name, with or without "Sea" ("Tyrrhenian"), or by
   a few Italian ones ("Tirreno", "mar Ligure"): 1, or 0 when none. */
int geo_area_find(const char *name, struct geo_area *a);
/* Whether the point is over the area. */
int geo_area_has(const struct geo_area *a, double lat, double lon);

/* The position in words, appended to b. */
void geo_describe(double lat, double lon, struct janas_buf *b);
/* The same as a JSON object, for a layout (services/common/template.h): "sea"
   when over one, "region" ("Sicily, Italy": the region over, or the first of
   the two a sea lies between), "and" (the second), "city", and "km" and
   "dir" from it when 3 km or more away. */
void geo_describe_json(double lat, double lon, struct janas_buf *b);

#endif
