#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Maurizio Cammalleri
"""Generates src/llm/unicode_data.h: code point ranges of the Unicode letter
(L*), number (N*) and mark (M*) categories and of the White_Space property, for the
pre-tokenizer of src/llm/tokenizer.c.

Usage: gen_unicode.py > src/llm/unicode_data.h
"""
import sys
import unicodedata

WHITE_SPACE = [(0x09, 0x0D), (0x20, 0x20), (0x85, 0x85), (0xA0, 0xA0),
               (0x1680, 0x1680), (0x2000, 0x200A), (0x2028, 0x2029),
               (0x202F, 0x202F), (0x205F, 0x205F), (0x3000, 0x3000)]


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    print(f"static const uint32_t {name}[][2] = {{")
    for a, b in rs:
        print(f"    {{0x{a:X}, 0x{b:X}}},")
    print("};")


cat = unicodedata.category
print("/* Generated by tools/gen_unicode.py from Unicode "
      f"{unicodedata.unidata_version}. Do not edit. */")
print("#ifndef JANAS_LLM_UNICODE_DATA_H\n#define JANAS_LLM_UNICODE_DATA_H\n")
print("#include <stdint.h>\n")
emit("janas_uni_letter", ranges(lambda c: cat(chr(c))[0] == "L"))
emit("janas_uni_number", ranges(lambda c: cat(chr(c))[0] == "N"))
emit("janas_uni_mark", ranges(lambda c: cat(chr(c))[0] == "M"))
emit("janas_uni_space", WHITE_SPACE)
print("\n#endif")
