#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Maurizio Cammalleri
"""
openapi_routes.py - the route table of janas-server, from OpenAI's OpenAPI
specification (https://github.com/openai/openai-openapi, openapi.json).

Every operation of the specification gets a row: those janas-server
implements name their handler, the others answer 501 with a message that
says why. Running it again on a newer specification keeps the table whole.

Usage: tools/openapi_routes.py openapi.json > src/server/routes.inc
       tools/openapi_routes.py openapi.json --coverage
"""
import hashlib
import json
import sys

# operationId -> handler in src/server/ (declared in routes.h)
HANDLERS = {
    "listModels": "srv_models_list",
    "retrieveModel": "srv_models_get",
    "createChatCompletion": "srv_chat_create",
    "createCompletion": "srv_completion_create",
    "deleteModel": "srv_models_delete",
    "listChatCompletions": "srv_stored_list",
    "getChatCompletion": "srv_stored_get",
    "updateChatCompletion": "srv_stored_update",
    "deleteChatCompletion": "srv_stored_delete",
    "getChatCompletionMessages": "srv_stored_messages",
    "createResponse": "srv_responses_create",
    "getResponse": "srv_responses_get",
    "deleteResponse": "srv_responses_delete",
    "cancelResponse": "srv_responses_cancel",
    "listInputItems": "srv_responses_input_items",
    "Getinputtokencounts": "srv_responses_input_tokens",
    "Compactconversation": "srv_responses_compact",
    "createConversation": "srv_conv_create",
    "getConversation": "srv_conv_get",
    "updateConversation": "srv_conv_update",
    "deleteConversation": "srv_conv_delete",
    "listConversationItems": "srv_conv_items_list",
    "createConversationItems": "srv_conv_items_create",
    "getConversationItem": "srv_conv_item_get",
    "deleteConversationItem": "srv_conv_item_delete",
    "createEmbedding": "srv_embeddings_create",
    "createModeration": "srv_moderations_create",
}

# What an operation that is not implemented is, by its tag: the text of the
# 501 answer. "planned" operations are ones a local text model can serve.
KIND = {
    "Chat": "planned",
    "Completions": "planned",
    "Models": "planned",
    "Responses": "planned",
    "Conversations": "planned",
    "Embeddings": "planned",
    "Moderations": "planned",
    "Files": "planned",
    "Uploads": "planned",
    "Batch": "planned",
    "Vector stores": "planned",
    "Assistants": "planned",
    "Evals": "planned",
    "Audio": "other_model",
    "Images": "other_model",
    "Videos": "other_model",
    "Realtime": "other_model",
    "Live": "other_model",
    "Fine-tuning": "training",
}
METHODS = ("get", "post", "put", "delete", "patch")


def operations(spec):
    seen = set()
    for path, ops in spec["paths"].items():
        bare = path.split("?")[0]  # "?beta=true" variants are the same route
        for method, op in ops.items():
            if method not in METHODS or (method, bare) in seen:
                continue
            seen.add((method, bare))
            tag = (op.get("tags") or ["-"])[0]
            yield method.upper(), bare, op.get("operationId", ""), tag


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    raw = open(sys.argv[1], "rb").read()
    spec = json.loads(raw)
    ops = sorted(operations(spec), key=lambda o: (o[1], o[0]))
    if "--coverage" in sys.argv[2:]:
        by = {}
        for _, _, oid, tag in ops:
            t = by.setdefault(tag, [0, 0])
            t[1] += 1
            t[0] += oid in HANDLERS
        done = sum(v[0] for v in by.values())
        print(f"{done} of {len(ops)} operations implemented")
        for tag, (d, n) in sorted(by.items()):
            print(f"  {tag:40} {d:3} / {n}")
        return
    ver = spec.get("info", {}).get("version", "?")
    print("/* Generated by tools/openapi_routes.py - do not edit.")
    print(f"   OpenAI OpenAPI {ver}, sha256 {hashlib.sha256(raw).hexdigest()},")
    print(f"   {len(ops)} operations, {sum(o[2] in HANDLERS for o in ops)}"
          " implemented. */")
    for method, path, oid, tag in ops:
        h = HANDLERS.get(oid, "NULL")
        kind = "implemented" if oid in HANDLERS else KIND.get(tag, "cloud")
        print(f"JANAS_ROUTE({method}, {c_str(path)}, {c_str(oid)}, "
              f"{c_str(tag)}, {kind}, {h})")


if __name__ == "__main__":
    main()
